export const StaffModel={
id:ID,
booking_url: String,
color_code: Int,
created_at: String,
description: String,
display_name: String,
display_order: Int,
email: String,
employement_from: String,
employement_to: String,
experience_month: Int,
experience_year: Int,
first_name: String,
gender: String,
staff_id: Int,
is_active: String,
is_service_provider: String,
last_name: String,
name: String,
phone_no: String,
phone_no_country: String,
commission: [staff_commission],
services: [staff_services],
sync: [staff_sync],
staff_timings: [staff_timings],
role: [String],
site_creator: Boolean,
site_id: String=1,
site_owener: Boolean,
sorting_id: Int,
workspace_id: Int,
is_deleted: Boolean,
}